function [frameVect] = frame_proj(a,l,s,x,k)
%GTP
%    GTP = GTP(A,LX,LY,LZ,S1,S3,X1,X3,X5,X7,X9,X11)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    13-Dec-2016 17:55:21

lx = l(1);
ly = l(2);
lz = l(3);

s1 = s(1);
s3 = s(3);

x1 = x(1);
x3 = x(2);
x5 = x(3);
x7 = x(4);
x9 = x(5);
x11 = x(6);

t2 = cos(a);
t3 = sin(s1);
t4 = sin(a);
t5 = cos(s1);
t6 = cos(x5);
t7 = sin(x1);
t8 = cos(x1);
t9 = sin(x3);
t10 = sin(x5);
t11 = t3.*t4;
t12 = t2.*t5;
t13 = t11+t12;
t14 = t6.*t7;
t21 = t8.*t9.*t10;
t15 = t14-t21;
t16 = t2.*t3;
t23 = t4.*t5;
t17 = t16-t23;
t18 = t7.*t10;
t19 = t6.*t8.*t9;
t20 = t18+t19;
t22 = cos(x3);
t24 = t6.*t8;
t25 = t7.*t9.*t10;
t26 = t24+t25;
t27 = t8.*t10;
t32 = t6.*t7.*t9;
t28 = t27-t32;
t29 = s3.*t2.*t5;
t30 = s3.*t3.*t4;
t31 = -ly+t29+t30;
t33 = s3.*t2.*t3;
t35 = s3.*t4.*t5;
t34 = lz+t33-t35;
gTp = reshape([-t15.*t17+t13.*t20,-t13.*t28+t17.*t26,t6.*t13.*t22+t10.*t17.*t22,0.0,-t13.*t15-t17.*t20,t13.*t26+t17.*t28,-t6.*t17.*t22+t10.*t13.*t22,0.0,-t8.*t22,-t7.*t22,t9,0.0,x7+t15.*t31+t20.*t34+lx.*t8.*t22,x9-t26.*t31-t28.*t34+lx.*t7.*t22,x11-lx.*t9+t6.*t22.*t34-t10.*t22.*t31,1.0],[4,4]);

gTh1 = gTh(x);
hTf1 = hTf(a,l);
fTp1 = fTp(s);

frameVect =  k*gTh1*hTf1*fTp1*eye(4,4);