function fTp = fTp(s)
%FTP
%    FTP = FTP(S1,S3)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    14-Dec-2016 23:05:31

s1 = s(1);%angle
s3 = s(3);%distance

t2 = cos(s1);
t3 = sin(s1);
fTp = reshape([0.0,t3,t2,0.0,0.0,t2,-t3,0.0,-1.0,0.0,0.0,0.0,0.0,-s3.*t2,s3.*t3,1.0],[4,4]);
