function gTh = gTh(x)
%GTH
%    GTH = GTH(X1,X3,X5,X7,X9,X11)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    13-Dec-2016 18:46:16

x1 = x(1);
x3 = x(2);
x5 = x(3);
x7 = x(4);
x9 = x(5);
x11 = x(6);

t2 = cos(x1);
t3 = sin(x1);
t4 = sin(x5);
t5 = cos(x5);
t6 = sin(x3);
t7 = cos(x3);
gTh = reshape([t2.*t7,t3.*t7,-t6,0.0,-t3.*t5+t2.*t4.*t6,t2.*t5+t3.*t4.*t6,t4.*t7,0.0,t3.*t4+t2.*t5.*t6,-t2.*t4+t3.*t5.*t6,t5.*t7,0.0,x7,x9,x11,1.0],[4,4]);
