function hTf = hTf(a,l)
%HTF
%    HTF = HTF(A,LX,LY,LZ)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    14-Dec-2016 22:35:37

lx = l(1);
ly = l(2);
lz = l(3);

t2 = sin(a);
t3 = cos(a);
hTf = reshape([1.0,0.0,0.0,0.0,0.0,t3,t2,0.0,0.0,-t2,t3,0.0,lx,ly,lz,1.0],[4,4]);
