function hTf = hTf(a,l)
%HTF
%    HTF = HTF(A,LX,LY,LZ)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    14-Dec-2016 22:35:37

% Rotation about z of 90 degrees to make the hand reference frame match with 
% what is expected for the mechanical chain reconstruction
T = [0 1 0 0;
    -1 0 0 0;
    0 0 1 0;
    0 0 0 1];

% Translation from hand to finger
lx = l(1);
ly = l(2);
lz = l(3);

% Rotation of alpha along X axis from hand to finger
t2 = sin(a);
t3 = cos(a);
hTf = reshape([1.0,0.0,0.0,0.0,0.0,t3,t2,0.0,0.0,-t2,t3,0.0,lx,ly,lz,1.0],[4,4]);
hTf =  T * hTf;